Enable Allure reporting and disable trace removals in workflow

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -23,10 +23,10 @@ jobs:
     - uses: actions/setup-node@v4
       with:
         node-version: lts/*
-    - name: Install zip
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y zip
+    # - name: Install zip
+    #   run: |
+    #     sudo apt-get update
+    #     sudo apt-get install -y zip
     - name: Install dependencies
       run: npm ci
     - name: Install Playwright Browsers
@@ -37,9 +37,9 @@ jobs:
     - name: Run Playwright tests (all projects)
       if: github.event.inputs.project == ''
       run: npx playwright test
-    - name: Remove network trace files from Playwright traces
-      if: always()
-      run: for zipfile in playwright-report/data/*.zip; do zip -d "$zipfile" 0-trace.network; done || true
+    # - name: Remove network trace files from Playwright traces
+    #   if: always()
+    #   run: for zipfile in playwright-report/data/*.zip; do zip -d "$zipfile" 0-trace.network; done || true
     - uses: actions/upload-artifact@v4
       if: always()
       with:
@@ -47,26 +47,26 @@ jobs:
         path: playwright-report/
         retention-days: 30
 
-    # - name: Get Allure history # Step to retrieve Allure history
-    #   uses: actions/checkout@v4
-    #   if: always() # Execute even if previous steps fail
-    #   continue-on-error: true # Continue execution even if the step fails
-    #   with:
-    #     ref: gh-pages # Specify the branch to retrieve Allure history from
-    #     path: gh-pages # Set the destination path for Allure history
+    - name: Get Allure history # Step to retrieve Allure history
+      uses: actions/checkout@v4
+      if: always() # Execute even if previous steps fail
+      continue-on-error: true # Continue execution even if the step fails
+      with:
+        ref: gh-pages # Specify the branch to retrieve Allure history from
+        path: gh-pages # Set the destination path for Allure history
 
-    # - name: Allure report action # Step to generate Allure report
-    #   uses: simple-elf/allure-report-action@master
-    #   if: always() # Execute even if previous steps fail
-    #   with:
-    #     allure_results: ${{ env.ALLURE_RESULTS_PATH }} # Specify the directory containing Allure results
-    #     allure_history: allure-history # Specify the directory to store Allure history
-    #     keep_reports: 5 # Specify the number of previous reports to keep
+    - name: Allure report action # Step to generate Allure report
+      uses: simple-elf/allure-report-action@master
+      if: always() # Execute even if previous steps fail
+      with:
+        allure_results: ${{ env.ALLURE_RESULTS_PATH }} # Specify the directory containing Allure results
+        allure_history: allure-history # Specify the directory to store Allure history
+        keep_reports: 5 # Specify the number of previous reports to keep
 
-    # - name: Deploy Allure report to GitHub Pages # Step to deploy Allure report to GitHub Pages
-    #   if: always() # Execute even if previous steps fail
-    #   uses: peaceiris/actions-gh-pages@v4
-    #   with:
-    #     github_token: ${{ secrets.GITHUB_TOKEN }} # Provide the GitHub token for authentication
-    #     publish_branch: gh-pages # Specify the branch to publish the report to
-    #     publish_dir: allure-history # Specify the directory containing the report
+    - name: Deploy Allure report to GitHub Pages # Step to deploy Allure report to GitHub Pages
+      if: always() # Execute even if previous steps fail
+      uses: peaceiris/actions-gh-pages@v4
+      with:
+        github_token: ${{ secrets.GITHUB_TOKEN }} # Provide the GitHub token for authentication
+        publish_branch: gh-pages # Specify the branch to publish the report to
+        publish_dir: allure-history # Specify the directory containing the report
